image: python

stages:
  - test
  - build
  - publish

before_script:
  - pip install -r requirements/test.txt
  - pip install tox

python34:
  image: python:3.4
  stage: test
  script: tox -epy34-django19 -epy34-django110 -epy34-django111 -epy34-django201 -epy34-djangomaster

python35:
  image: python:3.5
  stage: test
  script: tox -epy35-django19 -epy35-django110 -epy35-django111 -epy35-django201 -epy35-djangomaster

python36:
  image: python:3.6
  stage: test
  script: tox -epy36-django19 -epy36-django110 -epy36-django111 -epy36-django201 -epy36-djangomaster

coverage:
  stage: test
  script:
    - pip install tox
    - tox -e py36-django201
    - coverage html
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 day

docs:
  stage: build
  script:
    - cd docs/
    - pip install -r requirements.txt
    - rm -rf build/
    - make html
  artifacts:
    paths:
      - docs/build/html/
    expire_in: 1 day

pages:
  stage: publish
  script:
    - mkdir -p public/coverage
    - cp -fr docs/build/html/* public/
    - cp -fr htmlcov/* public/coverage/
  dependencies:
    - coverage
    - docs
  artifacts:
    paths:
      - public
  only:
    - master
