image: alpine

stages:
  - test
  - build

before_script:
  - apk --no-cache add py2-pip python-dev

test:
  stage: test
  script:
    - pip install tox
    - tox

pages:
  stage: build
  script:
  - cd docs/
  - pip install -r requirements.txt
  - apk --no-cache add make
  - rm -rf build/
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
