image: python:3.6

stages:
  - test
  - build
  - publish

before_script:
  - apt-get install python3.4 python3.5
  - pip install -r requirements/test.txt
  - pip install tox

test:
  stage: test
  script:
    - tox

coverage:
  stage: test
  script:
    - pip install tox
    - tox -e py36-django201
    - coverage html
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 day

docs:
  stage: build
  script:
    - cd docs/
    - pip install -r requirements.txt
    - apt-get install make
    - rm -rf build/
    - make html
  artifacts:
    paths:
      - docs/build/html/
    expire_in: 1 day

pages:
  stage: publish
  script:
    - mkdir -p public/coverage
    - cp -fr docs/build/html/* public/
    - cp -fr htmlcov/* public/coverage/
  dependencies:
    - coverage
    - docs
  artifacts:
    paths:
      - public
  only:
    - master
